services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sample.com
      PGADMIN_DEFAULT_PASSWORD: sample
    ports:
      - "8081:80"
    networks:
      - postgres_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
